spring:
  # DB源
  datasource:
    url: jdbc:mysql://localhost:3306/taurus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&&useSSL=false
    username: root
    password: root
  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'update'
  ## redis配置
  redis:
    host: localhost
    port: 6379
    # password: taurus
    database: 0
# 端口
server:
  port: 8080

# 文件上传路径
taurus:
  file-root-path: /home/taurus/static
# jwt开关
jwt:
  enable: false
# swagger开关
springfox:
  documentation:
    enabled: true
# jpa日志
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace