spring:
  # 环境 dev|test|prod
  profiles:
    active: @profileActive@
  application:
    name: taurus
  # 连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    properties:
    #      hibernate:
    #        enable_lazy_load_no_trans: true
    # json时间格式
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd  HH:mm:ss
    time-zone: GMT+8
  # servlet
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  # redis
  data:
    redis:
      repositories:
        enabled: false
# 服务器配置
server:
  tomcat:
    max-http-form-post-size: 20971520
  max-http-header-size: 1024000
#  servlet:
#    context-path: /api
# 日志配置
logging:
  level:
    root: info
    com.code.taurus: debug
  file:
    name: logs/taurus.log
    path: logs/taurus
# actuator
#management:
#  endpoint:
#    env:
#      enabled: true
#    health:
#      show-details: always
#  endpoints:
#    web:
#      base-path: /
#      exposure:
#        include: env,health
# jwt
jwt:
  iss: backend
  expire-time: 10800000
  enable: true
# swagger开关
springfox:
  documentation:
    enabled: false
# schedule
schedule:
  redis:
    refresh: 0 0 3 * * ? #0/30 * * * * ? ###
# 短信机制
sms:
  juhe:
    url: http://v.juhe.cn/sms/send
    tplId: 123
    limit: 60000
    appKey: 123
