spring:
  # DB源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taurus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        format_sql: true
  ## redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
# 端口
server:
  port: 80

# 文件上传路径
taurus:
  file-root-path: ./taurus
# jwt开关
jwt:
  enable: false
# swagger开关
swagger:
  enable: true
# jpa日志
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
